const socketEvents = {
    CHANGESTATUS: "CHANGESTATUS",

    READALLCHANNEL: "READALLCHANNEL",
    CREATECHANNEL: "CREATECHANNEL",
    READCHANNEL: "READCHANNEL",
    UPDATECHANNEL: "UPDATECHANNEL",
    DELETECHANNEL: "DELETECHANNEL",

    READALLMESSAGE: "READALLMESSAGE",
    CREATEMESSAGE: "CREATEMESSAGE",
    READMESSAGE: "READMESSAGE",
    UPDATEMESSAGE: "UPDATEMESSAGE",
    DELETEMESSAGE: "DELETEMESSAGE",

    PINNED: "PINNED",
    FILES: "FILES",
};

const status = {
    ON: "ON",
    FAILED: "fAILED",
    // ON: "ON",
};

export { status };

export default socketEvents;
