const socketEvents = {
    CHANGESTATUS: "CHANGESTATUS",

    READALLCHANNEL: "READALLCHANNEL",
    CREATECHANNEL: "CREATECHANNEL",
    READCHANNEL: "READCHANNEL",
    UPDATECHANNEL: "UPDATECHANNEL",
    DELETECHANNEL: "DELETECHANNEL",

    READALLMESSAGE: "READALLMESSAGE",
    CREATEMESSAGE: "CREATEMESSAGE",
    READMESSAGE: "READMESSAGE",
    UPDATEMESSAGE: "UPDATEMESSAGE",
    DELETEMESSAGE: "DELETEMESSAGE",
};

const STATUS = {
    ON: "ON",
    FAILED: "FAILED",
    // ON: "ON",
};

export { STATUS };

export default socketEvents;
